config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'

  get 'register', to: 'users#new'

  resource :user, only: %i[create] do
    post :login
    post :logout
  end

  resources :clock, only: %i[index new create edit update destroy]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clock.rb
# frozen_string_literal: true

class Clock < ApplicationRecord
  self.inheritance_column = :_type_disabled

  validates :type,
            presence: true,
            inclusion: {
              in: ['Clock::In', 'Clock::Out'],
              message: '%{value} is not a valid/supported clock type'
            }
  belongs_to :user, foreign_key: :user_id

  class In < Clock
    def type
      'in'
    end
  end

  class Out < Clock
    def type
      'out'
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :name, presence: true

  has_many :clocks, class_name: 'Clock', foreign_key: :user_id, dependent: :delete_all
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def authenticate(user)
    session[:current_user] = user.id
  end

  def authorize_user
    redirect_to root_path if current_user.nil?
  end

  def check_login
    redirect_to clock_index_path unless current_user.nil?
  end

  def current_user
    @current_user ||= User.find_by_id(session[:current_user])
  end
end

app/controllers/clock_controller.rb
# frozen_string_literal: true

class ClockController < ApplicationController
  before_action :authorize_user

  def index
    @clocks = current_user.clocks

    respond_to do |format|
      format.html { render(layout: 'application') }
      format.json do
        begin
          render json: ClockDatatable.new(view_context, clocks: @clocks)
        rescue ArgumentError => e
          render json: { error: e.message }, status: :bad_request
        end
      end
    end
  end

  def new
    @clock_event = Clock.new
  end

  def create
    @clock_event = current_user.clocks.new(
      type: clock_params[:type],
      details: clock_params[:details],
      clocked_at: clocked_time
    )

    if @clock_event.save
      redirect_to clock_index_path
    else
      render :new
    end
  end

  def edit
    redirect_to(root_path) unless clock
    @clock_event = clock
  end

  def update
    @clock_event = clock
    if @clock_event.update(type: clock_params[:type], details: clock_params[:details])
      redirect_to clock_index_path
    else
      render :edit
    end
  end

  def destroy
    clock.destroy
    redirect_to clock_index_path
  end

  private

  def clocked_time
    DateTime.parse(clock_params[:clocked_at])
  rescue StandardError
    Time.now
  end

  def clock
    Clock.find_by_id(params[:id])
  end

  def clock_params
    params.require(:clock).permit(:details, :type, :clocked_at)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :check_login, except: [:logout]
  before_action :authorize_user, only: [:logout]

  def index; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(name: user_param[:name], email: user_param[:email])
    if @user.save
      authenticate(@user)
      redirect_to clock_index_path
    else
      render :new
    end
  end

  def login
    @user = User.where(email: user_param[:email])[0]
    if @user
      authenticate(@user)
      redirect_to clock_index_path
    else
      flash[:error] = 'invalid email, please sign up!'
      render :index
    end
  end

  def logout
    @current_user = nil
    reset_session
    flash[:success] = 'successfully logged out'
    redirect_to root_path
  end

  private

  def user_param
    params.require(:user).permit(:email, :name)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/clock/_form.html.slim
.row
  .col-md-3
  .col-md-6
    h2.text-center.hi-mama-dark-blue = title
    .padded
    .padded
    .form-group
      h3.text-center.hi-mama-dark-blue#digital-clock
      .text-center
        small.hi-mama-light-blue#time-zone
    
    = simple_form_for @clock_event, url: path, method: method do |f|
      = f.hidden_field :clocked_at, input_html: { id: 'clocked_time' }
      .form-group
        small
          span.error-message
            = render 'shared/flash'
        = f.input :details, placeholder: 'Record extra information here', class: "form-control", label: false
      .padded
      .radio-group
        = f.label :type, 'Type:', class: 'radio-label'
        = f.input :type, as: :radio_buttons,
                  :item_wrapper_class => 'form-check-inline',
                  collection: [['Clock::In', 'Clock In'], ['Clock::Out', 'Clock Out']],
                  label_method: :second,
                  value_method: :first, label: false,
                  checked: ['Clock::In', 'Clock In'],
                  required: true
      .form-group.text-center
        = f.submit submit, class: "btn-submit"

app/views/clock/edit.html.slim
= render partial: "form", locals: { title: 'Edit Clock Event', path: clock_path(@clock_event.id), method: 'PUT', submit: 'Update' }

app/views/clock/index.html.slim
h5.text-right
  = link_to("Log out", logout_user_path, method: :post)

h4.hi-mama-light-blue Welcome #{current_user.name}
.padded
h2.hi-mama-dark-blue.text-center Clock History
.padded
= link_to("Add New Entry", new_clock_path, class: "btn btn-submit")
.padded
table#clock-datatable data-source="#{clock_index_path(format: :json)}"
  thead
    tr
      th 
      th Type
      th Time
      th Details
      th
      th

app/views/clock/new.html.slim
= render partial: "form", locals: { title: 'Log Clock In/Out', path:  clock_index_path, method: 'POST', submit: 'Log Event' }

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-light.bg-light
  .container
    .logo-wrapper 
      = link_to clock_index_path, class: "navbar-brand" do
        = image_tag "himama.webp", style: "width:100%"
    h1.nav-end
      span.hi-mama-light-blue Clock
      span.hi-mama-dark-blue It!

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Clockit
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/navbar'
    .container.padded
      = yield

app/views/shared/_flash.html.slim
- if !flash.empty?
  - flash.each do |key, message|
    div class=("flash #{key}") 
      span = flash[key] = message.try(:html_safe)
  - flash.clear

app/views/users/index.html.slim
.row
  .col-md-4
  .col-md-4.login-form
    h3.header.oblique.text-center Login to clock events
    = simple_form_for :user, url: login_user_path, method: :post do |f|
      .form-group
        small
          span.error-message
            = render 'shared/flash'
        = f.input :email, placeholder: "Your Email *", class: "form-control", label: false, type: "email"
      .form-group.text-center
        = f.button :submit, class: "btnSubmit", value: "Login"
    small
      .text-right(style="bottom: 0;")
        = link_to("Register new account", register_path, class: "hi-mama-dark-blue")

app/views/users/new.html.slim
.row
  .col-md-4
  .col-md-4.login-form
    h3 Create Account
    = simple_form_for @user, url: user_path, method: :post do |f|
      .form-group
        small
          span.error-message
            = render 'shared/flash'
        = f.label :name, 'Full Name:'
        = f.input :name, placeholder: "Full Name *", class: "form-control", label: false, required: true
        = f.label :email, 'Input your email:'
        = f.input :email, placeholder: "Your Email *", class: "form-control", label: false, required: true, type: 'email'
      .form-group.text-center
        = f.submit "Register", class: "btnSubmit"
    small
      .text-right(style="bottom: 0;")
        = link_to("Already have an account? Click Here", root_path, class: "hi-mama-dark-blue")